name: Publish Github Pages Geoexpress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout your repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        sudo apt-get update && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

    # 4. Run sphinx-apidoc
    - name: Generate API documentation
      run: |
        sphinx-apidoc -o docs docs

    # 5. Build the HTML docs (opcional)
    - name: Build HTML documentation
      run: |
        sphinx-build -b html docs docs/_build/html

    # 6. Build PDF documentation
    - name: Build PDF documentation
      run: |
        sphinx-build -b latex docs docs/_build/latex
        cd docs/_build/latex
        ls  # Verificar que el archivo .tex se ha generado
        latexmk -pdf -quiet -interaction=nonstopmode -f *.tex  # Compilar el archivo .tex generado

    # 7. Commit and push the generated documentation
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/_build/html docs/*.rst docs/_build/latex/Geoexpress.pdf
        git commit -m "Auto-update documentation"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
